[package]
name = "ownership-moves"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "basics"
path = "src/basics/main.rs"

[[bin]]
name = "moves"
path = "src/moves/main.rs"

[[bin]]
name = "drop-order"
path = "src/drop/main.rs"

[[bin]]
name = "copy-clone"
path = "src/copy-clone/main.rs"